### ISSUE TITLE
[Question] where i can find releases?

### ISSUE THREAD

**Issue by MuhammadBayiz** [KenAli77/InFit#1]
In apk i mean

**Comment by KenAli77** [comment]
Release is not ready yet, will be on September 4th.

**Comment by MuhammadBayiz** [comment]
What about test builds? I really like to try it possible

**Comment by KenAli77** [comment]
You can build the master with your own firebase server

**Comment by MuhammadBayiz** [comment]
Don't know how :(
I guess i should just wait.
